(defun fb-insert-pair (key value)
  (insert (format "        %s: %s\n" key value)))

(defun interactively-define-form ()
  (interactive)
  (let (done)
    (while (not done)
      (let* ((name (read-from-minibuffer "Field name? ")) 
             (label (read-with-default "Label? " name))
             (type (read-with-default "Type? " "text")))
        (beginning-of-line)
        (insert (format "    %s:\n" name))
        (fb-insert-pair "label" label)
        (fb-insert-pair "type" type))
      (while (not (y-or-n-p "Done? "))
        (let ((key (read-from-minibuffer "Key? "))
              (value (read-from-minibuffer "Value? ")))
          (fb-insert-pair key value)))
      (setq done (not (y-or-n-p "Another? "))))))
